eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.124:10001/eureka/

server:
  port: 60003
spring:
  application:
    name: service-feign
#开启断路器，默认关闭
feign:
  hystrix:
    enabled: true